[general]
import = ["kanagawa-wave.toml"]

[window]
opacity = 0.7
padding = { x = 10, y = 10 }
option_as_alt = "Both"

[font]
size = 12.5
# size = 15.5

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"


[colors.primary]
# foreground = "#dddddd"
background = "#000000"

# [colors]
# cursor = { cursor = "#dddddd" }
# vi_mode_cursor = { cursor = "#dddddd" }
#
# [colors.normal]
# black = "#000000"
# red = "#cc0403"
# green = "#19cb00"
# yellow = "#cecb00"
# blue = "#0d73cc"
# magenta = "#cb1ed1"
# cyan = "#0dcdcd"
# white = "#dddddd"
#
# [colors.bright]
# black = "#767676"
# red = "#f2201f"
# green = "#23fd00"
# yellow = "#fffd00"
# blue = "#1a8fff"
# magenta = "#fd28ff"
# cyan = "#14ffff"
# white = "#ffffff"


[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }


[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Back", mods = "Control",       chars  = "\u0017"            },
  { key = "C",    mods = "Control|Shift", action = "Copy"              },
  { key = "V",    mods = "Control|Shift", action = "Paste"             },
  { key = "T",    mods = "Control|Shift", action = "CreateNewTab"      },
  { key = "W",    mods = "Control|Shift", action = "Quit"              },
  { key = "Tab",  mods = "Control",       action = "SelectNextTab"     },
  { key = "Tab",  mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "1",    mods = "Alt",           action = "SelectTab1"        },
  { key = "2",    mods = "Alt",           action = "SelectTab2"        },
  { key = "3",    mods = "Alt",           action = "SelectTab3"        },
  { key = "4",    mods = "Alt",           action = "SelectTab4"        },
  { key = "5",    mods = "Alt",           action = "SelectTab5"        },
  { key = "6",    mods = "Alt",           action = "SelectTab6"        },
  { key = "7",    mods = "Alt",           action = "SelectTab7"        },
  { key = "8",    mods = "Alt",           action = "SelectTab8"        },
  { key = "9",    mods = "Alt",           action = "SelectLastTab"     },
]
